- hosts: localhost
  tasks:
  - ansible.builtin.debug:
      msg: "the value of foo.txt is {{ lookup('ansible.builtin.file', '/etc/hosts') }}"
  
  - name: display multiple file contents
    ansible.builtin.debug: var=item
    with_file:
      - "/etc/hosts"
      - "jj"  # will be looked in files/ dir relative to play or in role
